import "@/styles/global.scss";
import { HeaderComponent } from "@/components/common/Header";
import { FooterComponent } from "@/components/common/Footer";
import { SessionProviderWrapper } from "@/components/common/SessionProviderWrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <SessionProviderWrapper>
          <HeaderComponent />
          <main className="main-container">{children}</main>
          <FooterComponent />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
