import type { CardData } from './types';

/**
 * リージェント(アーリーアクセス) 全カードデータ。
 * 出典: https://wikiwiki.jp/sts2/%E3%83%AA%E3%83%BC%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%28%E3%82%A2%E3%83%BC%E3%83%AA%E3%83%BC%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%29
 * baseValue/plusValueは主効果（ダメージ/ブロック）の数値のみを抽出したもの。
 * aggregatable=falseのカードは条件付き効果・Xコスト・パワーカード等のため、
 * 総威力/総ブロックの自動集計対象から除外する（所持枚数のカウントは行う）。
 * starGainBase/Plusは「✦を得る」表現から抽出したスター回収数（該当なしはnull）。
 */
export const CARDS: CardData[] = [
  {
    id: 'attack-01',
    name: 'ストライク',
    type: 'attack',
    rarity: 'スターター',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 6,
    plusValue: 9,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '6ダメージを与える。',
    effectPlus: '9ダメージを与える。',
  },
  {
    id: 'attack-02',
    name: '落星',
    type: 'attack',
    rarity: 'スターター',
    energyCostBase: 0,
    starCostBase: 2,
    energyCostPlus: 0,
    starCostPlus: 2,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 12,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ダメージを与える。脱力1を付与する。弱体1を付与する。',
    effectPlus: '12ダメージを与える。脱力1を付与する。弱体1を付与する。',
  },
  {
    id: 'attack-03',
    name: '衝突軌道',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 11,
    plusValue: 15,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '11ダメージを与える。デブリを1枚手札に加える。',
    effectPlus: '15ダメージを与える。デブリを1枚手札に加える。',
  },
  {
    id: 'attack-04',
    name: '星霊の波動',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 0,
    starCostBase: 3,
    energyCostPlus: 0,
    starCostPlus: 3,
    valueKind: 'damage',
    baseValue: 12,
    plusValue: 16,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に6ダメージを2回与える。',
    effectPlus: 'すべての敵に8ダメージを2回与える。',
  },
  {
    id: 'attack-05',
    name: 'ソーラーストライク',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 9,
    plusValue: 10,
    aggregatable: true,
    starGainBase: 1,
    starGainPlus: 2,
    effectBase: '9ダメージを与える。✦を得る。',
    effectPlus: '10ダメージを与える。✦✦を得る。',
  },
  {
    id: 'attack-06',
    name: 'フォトンカット',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 10,
    plusValue: 13,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '10ダメージを与える。カードを1枚引く。手札からカードを1枚選び、山札の一番上に置く。',
    effectPlus: '13ダメージを与える。カードを2枚引く。手札からカードを1枚選び、山札の一番上に置く。',
  },
  {
    id: 'attack-07',
    name: '三日月の槍',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 1,
    energyCostPlus: 1,
    starCostPlus: 1,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 8,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ダメージを与える。✦をコストに持つすべてのカード1枚につき、追加で2ダメージを与える。',
    effectPlus: '8ダメージを与える。✦をコストに持つすべてのカード1枚につき、追加で3ダメージを与える。',
  },
  {
    id: 'attack-08',
    name: '重圧',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 7,
    plusValue: 8,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に7ダメージを与える。ターン終了時まですべての敵は筋力1を失う。',
    effectPlus: 'すべての敵に8ダメージを与える。ターン終了時まですべての敵は筋力2を失う。',
  },
  {
    id: 'attack-09',
    name: '刃の戦錬',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 7,
    plusValue: 9,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '7ダメージを与える。鍛造7。',
    effectPlus: '9ダメージを与える。鍛造9。',
  },
  {
    id: 'attack-10',
    name: '導きの星',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 2,
    energyCostPlus: 1,
    starCostPlus: 2,
    valueKind: 'damage',
    baseValue: 12,
    plusValue: 13,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '12ダメージを与える。カードを2枚引く。',
    effectPlus: '13ダメージを与える。カードを3枚引く。',
  },
  {
    id: 'attack-11',
    name: '天の力',
    type: 'attack',
    rarity: 'コモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 18,
    plusValue: 24,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '6ダメージを3回与える。',
    effectPlus: '6ダメージを4回与える。',
  },
  {
    id: 'attack-12',
    name: 'ガンマブラスト',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 3,
    energyCostPlus: 0,
    starCostPlus: 3,
    valueKind: 'damage',
    baseValue: 13,
    plusValue: 18,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '13ダメージを与える。脱力2を付与する。弱体2を付与する。',
    effectPlus: '18ダメージを与える。脱力2を付与する。弱体2を付与する。',
  },
  {
    id: 'attack-13',
    name: '輝きの奔流',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 3,
    plusValue: 4,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'このターンに得た✦一つにつき、すべての敵に3ダメージを与える。',
    effectPlus: 'このターンに得た✦一つにつき、すべての敵に4ダメージを与える。',
  },
  {
    id: 'attack-14',
    name: '月光波',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 4,
    plusValue: 5,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'このターンにプレイしたスキル1枚につき、4ダメージを与える。',
    effectPlus: 'このターンにプレイしたスキル1枚につき、5ダメージを与える。',
  },
  {
    id: 'attack-15',
    name: '星屑',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: null,
    energyCostPlus: 0,
    starCostPlus: null,
    valueKind: 'damage',
    baseValue: 5,
    plusValue: 7,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムな敵に5ダメージをX回与える。',
    effectPlus: 'ランダムな敵に7ダメージをX回与える。',
  },
  {
    id: 'attack-16',
    name: 'シャイニングストライク',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 11,
    aggregatable: true,
    starGainBase: 2,
    starGainPlus: 2,
    effectBase: '8ダメージを与える。✦✦を得る。このカードを山札の一番上に置く。',
    effectPlus: '11ダメージを与える。✦✦を得る。このカードを山札の一番上に置く。',
  },
  {
    id: 'attack-17',
    name: '王様パンチ',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 10,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ダメージを与える。このカードを引くたび、戦闘終了までダメージが4増加する。',
    effectPlus: '10ダメージを与える。このカードを引くたび、戦闘終了までダメージが6増加する。',
  },
  {
    id: 'attack-18',
    name: '撃滅',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 4,
    energyCostPlus: 1,
    starCostPlus: 4,
    valueKind: 'damage',
    baseValue: 30,
    plusValue: 40,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '30ダメージを与える。',
    effectPlus: '40ダメージを与える。',
  },
  {
    id: 'attack-19',
    name: '超大質量',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 5,
    plusValue: 5,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '5ダメージを与える。この戦闘で作成したカード1枚につき、追加で3ダメージを与える。',
    effectPlus: '5ダメージを与える。この戦闘で作成したカード1枚につき、追加で4ダメージを与える。',
  },
  {
    id: 'attack-20',
    name: '覇権',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 15,
    plusValue: 18,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '15ダメージを与える。次のターン、✷✷を得る。',
    effectPlus: '18ダメージを与える。次のターン、✷✷✷を得る。',
  },
  {
    id: 'attack-21',
    name: 'ノックアウト',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 30,
    plusValue: 38,
    aggregatable: true,
    starGainBase: 5,
    starGainPlus: 5,
    effectBase: '30ダメージを与える。このカードでとどめを刺した時、✦✦✦✦✦を得る。',
    effectPlus: '38ダメージを与える。このカードでとどめを刺した時、✦✦✦✦✦を得る。',
  },
  {
    id: 'attack-22',
    name: '王様キック',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 4,
    starCostBase: 0,
    energyCostPlus: 4,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 27,
    plusValue: 35,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '27ダメージを与える。このカードを引くたび、コストが1減少する。',
    effectPlus: '35ダメージを与える。このカードを引くたび、コストが1減少する。',
  },
  {
    id: 'attack-23',
    name: 'ヘヴンリードリル',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: null,
    starCostBase: 0,
    energyCostPlus: null,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 10,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ダメージをX回与える。Xが4以上なら、Xを2倍にする。',
    effectPlus: '10ダメージをX回与える。Xが4以上なら、Xを2倍にする。',
  },
  {
    id: 'attack-24',
    name: '実行せよ',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 6,
    plusValue: 9,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '6ダメージを与える。1ターンの間に、スキルを3枚プレイするたび、これを手札に戻す。',
    effectPlus: '9ダメージを与える。1ターンの間に、スキルを3枚プレイするたび、これを手札に戻す。',
  },
  {
    id: 'attack-25',
    name: '彗星',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 5,
    energyCostPlus: 0,
    starCostPlus: 5,
    valueKind: 'damage',
    baseValue: 33,
    plusValue: 44,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '33ダメージを与える。脱力3を付与する。弱体3を付与する。',
    effectPlus: '44ダメージを与える。脱力3を付与する。弱体3を付与する。',
  },
  {
    id: 'attack-26',
    name: '星の終わり',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 3,
    energyCostPlus: 1,
    starCostPlus: 3,
    valueKind: 'damage',
    baseValue: 9,
    plusValue: 11,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'エセリアル。すべての敵に9ダメージを与える。ターン終了時まですべての敵は筋力9を失う。',
    effectPlus: 'エセリアル。すべての敵に11ダメージを与える。ターン終了時まですべての敵は筋力11を失う。',
  },
  {
    id: 'attack-27',
    name: '叩き直してやる',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 5,
    plusValue: 7,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '5ダメージを与える。鍛造5。このターンに対象の敵へ攻撃していた回数（これを除く）1回につき、追加で鍛造5。',
    effectPlus: '7ダメージを与える。鍛造7。このターンに対象の敵へ攻撃していた回数（これを除く）1回につき、追加で鍛造7。',
  },
  {
    id: 'attack-28',
    name: '不時着',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 21,
    plusValue: 26,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に21ダメージを与える。手札をデブリで満たす。',
    effectPlus: 'すべての敵に26ダメージを与える。手札をデブリで満たす。',
  },
  {
    id: 'attack-29',
    name: 'セブンスターズ',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 7,
    energyCostPlus: 1,
    starCostPlus: 7,
    valueKind: 'damage',
    baseValue: 49,
    plusValue: 49,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に7ダメージを7回与える。',
    effectPlus: 'すべての敵に7ダメージを7回与える。',
  },
  {
    id: 'attack-30',
    name: '家宝のハンマー',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 20,
    plusValue: 25,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '20ダメージを与える。手札にある無色カードを1枚選び、そのコピーを1枚手札に加える。',
    effectPlus: '25ダメージを与える。手札にある無色カードを1枚選び、そのコピーを1枚手札に加える。',
  },
  {
    id: 'attack-31',
    name: '爆撃',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 18,
    plusValue: 24,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '18ダメージを与える。ターン開始時、これが廃棄札にある場合、それをプレイする。廃棄。',
    effectPlus: '24ダメージを与える。ターン開始時、これが廃棄札にある場合、それをプレイする。廃棄。',
  },
  {
    id: 'attack-32',
    name: '流星群',
    type: 'attack',
    rarity: 'エンシェント',
    energyCostBase: 0,
    starCostBase: 2,
    energyCostPlus: 0,
    starCostPlus: 2,
    valueKind: 'damage',
    baseValue: 14,
    plusValue: 21,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に14ダメージを与える。すべての敵に脱力2と弱体2を付与する。',
    effectPlus: 'すべての敵に21ダメージを与える。すべての敵に脱力2と弱体2を付与する。',
  },
  {
    id: 'skill-01',
    name: '防御',
    type: 'skill',
    rarity: 'スターター',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 5,
    plusValue: 8,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '5ブロックを得る。',
    effectPlus: '8ブロックを得る。',
  },
  {
    id: 'skill-02',
    name: '畏敬',
    type: 'skill',
    rarity: 'スターター',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 2,
    starGainPlus: 3,
    effectBase: '✦✦を得る。',
    effectPlus: '✦✦✦を得る。',
  },
  {
    id: 'skill-03',
    name: '身の程を知れ',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '脱力1を付与する。弱体1を付与する。廃棄。',
    effectPlus: '脱力1を付与する。弱体1を付与する。',
  },
  {
    id: 'skill-04',
    name: '星の外套',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 0,
    starCostBase: 1,
    energyCostPlus: 0,
    starCostPlus: 1,
    valueKind: 'block',
    baseValue: 7,
    plusValue: 10,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '7ブロックを得る。',
    effectPlus: '10ブロックを得る。',
  },
  {
    id: 'skill-05',
    name: '隠し財産',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 4,
    starGainPlus: 5,
    effectBase: '✦を得る。次のターン、✦✦✦を得る。',
    effectPlus: '✦を得る。次のターン、✦✦✦✦を得る。',
  },
  {
    id: 'skill-06',
    name: '宇宙的無関心',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 6,
    plusValue: 9,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '6ブロックを得る。捨て札のカードを1枚山札の一番上に置く。',
    effectPlus: '9ブロックを得る。捨て札のカードを1枚山札の一番上に置く。',
  },
  {
    id: 'skill-07',
    name: '輝き',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 1,
    starGainPlus: 2,
    effectBase: '✦を得る。カードを1枚引く。次のターン、カードを1枚引く。',
    effectPlus: '✦✦を得る。カードを1枚引く。次のターン、カードを1枚引く。',
  },
  {
    id: 'skill-08',
    name: '剣の研磨',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '鍛造9。次のターン、✷を得る。',
    effectPlus: '鍛造13。次のターン、✷を得る。',
  },
  {
    id: 'skill-09',
    name: '光の集約',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 8,
    plusValue: 11,
    aggregatable: true,
    starGainBase: 1,
    starGainPlus: 1,
    effectBase: '8ブロックを得る。✦を得る。',
    effectPlus: '11ブロックを得る。✦を得る。',
  },
  {
    id: 'skill-10',
    name: '失せよ！',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '手札のカードを1枚選び、ミニオンストライクに変化させる。',
    effectPlus: '手札のカードを1枚選び、ミニオンストライク+に変化させる。',
  },
  {
    id: 'skill-11',
    name: '小盾の展開',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 8,
    plusValue: 10,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ブロックを得る。活力2を得る。',
    effectPlus: '10ブロックを得る。活力3を得る。',
  },
  {
    id: 'skill-12',
    name: '戦利品',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '鍛造5。カードを2枚引く。',
    effectPlus: '鍛造8。カードを2枚引く。',
  },
  {
    id: 'skill-13',
    name: '煌めく激流',
    type: 'skill',
    rarity: 'コモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 11,
    plusValue: 13,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '11ブロックを得る。次のターン、5ブロックを得る。',
    effectPlus: '13ブロックを得る。次のターン、7ブロックを得る。',
  },
  {
    id: 'skill-14',
    name: 'クエーサー',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 2,
    energyCostPlus: 0,
    starCostPlus: 2,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムな無色カード3枚の中から1枚選び、手札に加える。',
    effectPlus: 'ランダムなアップグレード済みの無色カード3枚の中から1枚選び、手札に加える。',
  },
  {
    id: 'skill-15',
    name: 'モノローグ',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'このターン、カードをプレイするたび、ターン終了時まで筋力1を得る。',
    effectPlus: '保留。このターン、カードをプレイするたび、ターン終了時まで筋力1を得る。',
  },
  {
    id: 'skill-16',
    name: 'ロイヤルギャンブル',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 5,
    energyCostPlus: 0,
    starCostPlus: 5,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 9,
    starGainPlus: 9,
    effectBase: '9✦を得る。廃棄。',
    effectPlus: '保留。9✦を得る。廃棄。',
  },
  {
    id: 'skill-17',
    name: '星の巡り',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 3,
    energyCostPlus: 0,
    starCostPlus: 3,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '✷✷を得る。',
    effectPlus: '✷✷✷を得る。',
  },
  {
    id: 'skill-18',
    name: '粒子障壁',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 2,
    energyCostPlus: 0,
    starCostPlus: 2,
    valueKind: 'block',
    baseValue: 9,
    plusValue: 12,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '9ブロックを得る。このカードを手札に戻す。',
    effectPlus: '12ブロックを得る。このカードを手札に戻す。',
  },
  {
    id: 'skill-19',
    name: 'テラフォーミング',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '活力6を得る。',
    effectPlus: '活力8を得る。',
  },
  {
    id: 'skill-20',
    name: '共鳴',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 3,
    energyCostPlus: 1,
    starCostPlus: 3,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '筋力1を得る。すべての敵は筋力1を失う。',
    effectPlus: '筋力2を得る。すべての敵は筋力1を失う。',
  },
  {
    id: 'skill-21',
    name: '権威の体現',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 7,
    plusValue: 8,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '7ブロックを得る。ランダムな無色カードを1枚手札に加える。',
    effectPlus: '8ブロックを得る。ランダムなアップグレード済みの無色カードを1枚手札に加える。',
  },
  {
    id: 'skill-22',
    name: '顕現',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'あらゆる場所からソヴリン・ブレードを手札に加える。鍛造8。',
    effectPlus: 'あらゆる場所からソヴリン・ブレードを手札に加える。鍛造11。',
  },
  {
    id: 'skill-23',
    name: '集約',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 1,
    starGainPlus: 2,
    effectBase: '次のターン、✷と✦を得る。このターン、手札をすべて保留する。',
    effectPlus: '次のターン、✷と✦✦を得る。このターン、手札をすべて保留する。',
  },
  {
    id: 'skill-24',
    name: '征服者',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '鍛造3。このターン、ソヴリン・ブレードは対象の敵に2倍のダメージを与える。',
    effectPlus: '鍛造5。このターン、ソヴリン・ブレードは対象の敵に2倍のダメージを与える。',
  },
  {
    id: 'skill-25',
    name: '突撃せよ！',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札のカード2枚を選び、ミニオンの特攻に変化させる。',
    effectPlus: '山札のカード2枚を選び、ミニオンの特攻+に変化させる。',
  },
  {
    id: 'skill-26',
    name: '反射',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 3,
    energyCostPlus: 1,
    starCostPlus: 3,
    valueKind: 'block',
    baseValue: 15,
    plusValue: 20,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '15ブロックを得る。このターン、ブロックしたアタックによるダメージを、攻撃してきた敵に跳ね返す。',
    effectPlus: '20ブロックを得る。このターン、ブロックしたアタックによるダメージを、攻撃してきた敵に跳ね返す。',
  },
  {
    id: 'skill-27',
    name: '微光',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを3枚引く。手札からカードを1枚選び、山札の一番上に置く。',
    effectPlus: 'カードを4枚引く。手札からカードを1枚選び、山札の一番上に置く。',
  },
  {
    id: 'skill-28',
    name: '城壁',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 12,
    plusValue: 15,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '12ブロックを得る。鍛造10。',
    effectPlus: '15ブロックを得る。鍛造13。',
  },
  {
    id: 'skill-29',
    name: '予言',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを6枚引く。',
    effectPlus: 'カードを9枚引く。',
  },
  {
    id: 'skill-30',
    name: 'ビッグバン',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 1,
    starGainPlus: 1,
    effectBase: 'カードを1枚引く。✷を得る。✦を得る。鍛造5。廃棄。',
    effectPlus: '天賦。カードを1枚引く。✷を得る。✦を得る。鍛造5。廃棄。',
  },
  {
    id: 'skill-31',
    name: '悩ましい選択',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 6,
    energyCostPlus: 0,
    starCostPlus: 6,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを3枚引く。手札にあるスキルを1枚選び、それを3回プレイする。廃棄。',
    effectPlus: 'カードを5枚引く。手札にあるスキルを1枚選び、それを3回プレイする。廃棄。',
  },
  {
    id: 'skill-32',
    name: '我に死角なし',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 10,
    plusValue: 13,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '10ブロックを得る。ターン終了時、これが山札の一番上にある場合、自動的にプレイする。',
    effectPlus: '13ブロックを得る。ターン終了時、これが山札の一番上にある場合、自動的にプレイする。',
  },
  {
    id: 'skill-33',
    name: '確定事項',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '次のターン、山札からカードを2枚手札に加える。',
    effectPlus: '次のターン、山札からカードを3枚手札に加える。',
  },
  {
    id: 'skill-34',
    name: '思いがけぬ贈り物',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムな無色カードを3枚手札に加える。廃棄。',
    effectPlus: 'ランダムな無色カードを4枚手札に加える。廃棄。',
  },
  {
    id: 'skill-35',
    name: '鍛冶師',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 4,
    energyCostPlus: 1,
    starCostPlus: 4,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '鍛造30。',
    effectPlus: '鍛造40。',
  },
  {
    id: 'skill-36',
    name: '盾となれ！！',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '手札からカードを任意の枚数選び、ミニオンの盾に変化させる。廃棄。',
    effectPlus: '手札からカードを任意の枚数選び、ミニオンの盾+に変化させる。廃棄。',
  },
  {
    id: 'power-01',
    name: 'パリィ',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 10,
    plusValue: 14,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ソヴリン・ブレードが10ブロックを得るようになる。',
    effectPlus: 'ソヴリン・ブレードが14ブロックを得るようになる。',
  },
  {
    id: 'power-02',
    name: 'ブラックホール',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 3,
    plusValue: 4,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '✦を使用するか得るたび、すべての敵に3ダメージを与える。',
    effectPlus: '✦を使用するか得るたび、すべての敵に4ダメージを与える。',
  },
  {
    id: 'power-03',
    name: 'ペイル・ブルー・ドット',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '1ターンの間にカードを5枚以上プレイした場合、次のターン開始時、カードを1枚引く。',
    effectPlus: '1ターンの間にカードを5枚以上プレイした場合、次のターン開始時、カードを2枚引く。',
  },
  {
    id: 'power-04',
    name: '星の子',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 2,
    plusValue: 3,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '✦を消費するたび、消費した✦1つにつき2ブロックを得る。',
    effectPlus: '✦を消費するたび、消費した✦1つにつき3ブロックを得る。',
  },
  {
    id: 'power-05',
    name: '創造の柱',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 3,
    plusValue: 4,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを1枚作成するたび、3ブロックを得る。',
    effectPlus: 'カードを1枚作成するたび、4ブロックを得る。',
  },
  {
    id: 'power-06',
    name: '溶鉱炉',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、鍛造5。',
    effectPlus: 'ターン開始時、鍛造7。',
  },
  {
    id: 'power-07',
    name: 'オービット',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '4✷を消費するたび、✷を得る。',
    effectPlus: '4✷を消費するたび、✷を得る。',
  },
  {
    id: 'power-08',
    name: 'スペクトラムシフト',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、ランダムな無色カードを1枚手札に加える。',
    effectPlus: 'ターン開始時、ランダムな無色カードを1枚手札に加える。',
  },
  {
    id: 'power-09',
    name: 'ニュートロン・イージス',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 5,
    energyCostPlus: 1,
    starCostPlus: 5,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'プレート8を得る。',
    effectPlus: 'プレート11を得る。',
  },
  {
    id: 'power-10',
    name: 'ロイヤリティ',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '戦闘終了時、30ゴールドを獲得する。',
    effectPlus: '戦闘終了時、40ゴールドを獲得する。',
  },
  {
    id: 'power-11',
    name: '専制',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、カードを1枚引き、手札のカードを1枚廃棄する。',
    effectPlus: '天賦。ターン開始時、カードを1枚引き、手札のカードを1枚廃棄する。',
  },
  {
    id: 'power-12',
    name: '追尾の刃',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '鍛造7。ソヴリン・ブレードがすべての敵にダメージを与えるようになる。',
    effectPlus: '鍛造11。ソヴリン・ブレードがすべての敵にダメージを与えるようになる。',
  },
  {
    id: 'power-13',
    name: '武器庫',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを作成するたび、筋力1を得る。',
    effectPlus: '天賦。カードを作成するたび、筋力1を得る。',
  },
  {
    id: 'power-14',
    name: 'ジェネシス',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 2,
    starGainPlus: 3,
    effectBase: 'ターン開始時、✦✦を得る。',
    effectPlus: 'ターン開始時、✦✦✦を得る。',
  },
  {
    id: 'power-15',
    name: '君主の睨み',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '敵を攻撃するたび、その敵はターン終了時まで筋力1を失う。',
    effectPlus: '敵を攻撃するたび、その敵はターン終了時まで筋力1を失う。',
  },
  {
    id: 'power-16',
    name: '剣聖',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ソヴリン・ブレードがリプレイ1を得る。',
    effectPlus: 'ソヴリン・ブレードがリプレイ1を得る。',
  },
  {
    id: 'power-17',
    name: '虚無化',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターンを終了する。毎ターン、最初の2枚のカードを、コストを支払わずにプレイできる。エセリアル。',
    effectPlus: 'ターンを終了する。毎ターン、最初の2枚のカードを、コストを支払わずにプレイできる。',
  },
  {
    id: 'power-18',
    name: '封印されし玉座',
    type: 'power',
    rarity: 'エンシェント',
    energyCostBase: 1,
    starCostBase: 3,
    energyCostPlus: 0,
    starCostPlus: 3,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: 1,
    starGainPlus: 1,
    effectBase: 'カードをプレイするたび、✦を得る。',
    effectPlus: 'カードをプレイするたび、✦を得る。',
  },
];
