import type { CardData } from './types';

/**
 * 全クラス共通(アーリーアクセス)の無色カード。リージェント専用カードとは別に管理する。
 * 出典: https://wikiwiki.jp/sts2/%E5%85%A8%E3%82%AF%E3%83%A9%E3%82%B9%E5%85%B1%E9%80%9A%28%E3%82%A2%E3%83%BC%E3%83%AA%E3%83%BC%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%29
 * フィールドの意味はCARDS(cards.ts)と同じ。無色カードにスターコストは存在しないため常に0またはnull。
 */
export const COLORLESS_CARDS: CardData[] = [
  {
    id: 'colorless-attack-01',
    name: '一閃',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 5,
    plusValue: 8,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '5ダメージを与える。カードを1枚引く。',
    effectPlus: '8ダメージを与える。カードを1枚引く。',
  },
  {
    id: 'colorless-attack-02',
    name: '劇的な入場',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 11,
    plusValue: 15,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '天賦。すべての敵に11ダメージを与える。廃棄。',
    effectPlus: '天賦。すべての敵に15ダメージを与える。廃棄。',
  },
  {
    id: 'colorless-attack-03',
    name: '四方斬り',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 8,
    plusValue: 11,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '8ダメージを与える。与えたダメージと同じダメージを、他のすべての敵に与える。',
    effectPlus: '11ダメージを与える。与えたダメージと同じダメージを、他のすべての敵に与える。',
  },
  {
    id: 'colorless-attack-04',
    name: '連射',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: null,
    starCostBase: 0,
    energyCostPlus: null,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 10,
    plusValue: 14,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムな敵に10ダメージをX回与える。',
    effectPlus: 'ランダムな敵に14ダメージをX回与える。',
  },
  {
    id: 'colorless-attack-05',
    name: 'シーカーストライク',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 9,
    plusValue: 12,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '9ダメージを与える。山札のランダムなカード3枚から1枚選び、手札に加える。',
    effectPlus: '12ダメージを与える。山札のランダムなカード3枚から1枚選び、手札に加える。',
  },
  {
    id: 'colorless-attack-06',
    name: 'マインドブラスト',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '天賦。山札の枚数に等しいダメージを与える。',
    effectPlus: '天賦。山札の枚数に等しいダメージを与える。',
  },
  {
    id: 'colorless-attack-07',
    name: '究極のストライク',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 14,
    plusValue: 20,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '14ダメージを与える。',
    effectPlus: '20ダメージを与える。',
  },
  {
    id: 'colorless-attack-08',
    name: '共鳴の手斧',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 11,
    plusValue: 14,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '11ダメージを与える。次のターン開始時、これを手札に戻す。',
    effectPlus: '14ダメージを与える。次のターン開始時、これを手札に戻す。',
  },
  {
    id: 'colorless-attack-09',
    name: '拳闘',
    type: 'attack',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 7,
    plusValue: 9,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '7ダメージを与える。与えたダメージに等しいブロックを得る。',
    effectPlus: '9ダメージを与える。与えたダメージに等しいブロックを得る。',
  },
  {
    id: 'colorless-attack-10',
    name: 'ボーラ',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 3,
    plusValue: 4,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '3ダメージを与える。次のターン開始時、これを手札に戻す。',
    effectPlus: '4ダメージを与える。次のターン開始時、これを手札に戻す。',
  },
  {
    id: 'colorless-attack-11',
    name: '一斉射撃',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 12,
    plusValue: 16,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '12ダメージを与える。このターン、手札をすべて保留する。',
    effectPlus: '16ダメージを与える。このターン、手札をすべて保留する。',
  },
  {
    id: 'colorless-attack-12',
    name: '金の斧',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'この戦闘中にプレイしたカードの枚数に等しいダメージを与える。',
    effectPlus: '保留。この戦闘中にプレイしたカードの枚数に等しいダメージを与える。',
  },
  {
    id: 'colorless-attack-13',
    name: '強欲の手',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 20,
    plusValue: 25,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '20ダメージを与える。リーサル時、20ゴールドを得る。',
    effectPlus: '25ダメージを与える。リーサル時、25ゴールドを得る。',
  },
  {
    id: 'colorless-attack-14',
    name: '裂傷',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 15,
    plusValue: 18,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '15ダメージを与える。対象の敵に付与しているデバフ1種類につき、追加で5ダメージを与える。',
    effectPlus: '18ダメージを与える。対象の敵に付与しているデバフ1種類につき、追加で8ダメージを与える。',
  },
  {
    id: 'colorless-attack-15',
    name: 'ジャックポット',
    type: 'attack',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 25,
    plusValue: 30,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '25ダメージを与える。ランダムなコスト0●のカードを3枚手札に加える。',
    effectPlus: '30ダメージを与える。ランダムなアップグレード済みのコスト0●のカードを3枚手札に加える。',
  },
  {
    id: 'colorless-skill-01',
    name: '闇の足枷',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン終了時まで敵は筋力9を失う。廃棄。',
    effectPlus: 'ターン終了時まで敵は筋力15を失う。廃棄。',
  },
  {
    id: 'colorless-skill-02',
    name: '延長',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '次のターン、現在のブロック値に等しいブロックを得る。廃棄。',
    effectPlus: '次のターン、現在のブロック値に等しいブロックを得る。',
  },
  {
    id: 'colorless-skill-03',
    name: '何でも屋',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムな無色カードを1枚手札に加える。廃棄。',
    effectPlus: 'ランダムな無色カードを2枚手札に加える。廃棄。',
  },
  {
    id: 'colorless-skill-04',
    name: '苛立ち',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '保留。手札が0枚の場合、カードを2枚引き、●●を得る。',
    effectPlus: '保留。手札が0枚の場合、カードを3枚引き、●●●を得る。',
  },
  {
    id: 'colorless-skill-05',
    name: '技巧',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 4,
    plusValue: 7,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '4ブロックを得る。カードを1枚引く。',
    effectPlus: '7ブロックを得る。カードを1枚引く。',
  },
  {
    id: 'colorless-skill-06',
    name: '焦燥',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '手札にアタックがない場合、カードを2枚引く。',
    effectPlus: '手札にアタックがない場合、カードを3枚引く。',
  },
  {
    id: 'colorless-skill-07',
    name: '生産',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '●●を得る。廃棄。',
    effectPlus: '●●●を得る。廃棄。',
  },
  {
    id: 'colorless-skill-08',
    name: '非常ボタン',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 30,
    plusValue: 40,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '30ブロックを得る。2ターンの間、カードからブロックを得ることができない。廃棄。',
    effectPlus: '40ブロックを得る。2ターンの間、カードからブロックを得ることができない。廃棄。',
  },
  {
    id: 'colorless-skill-09',
    name: '予測',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを2枚引く。手札からカードを1枚、山札の一番上に置く。廃棄。',
    effectPlus: 'カードを2枚引く。手札からカードを1枚、山札の一番上に置く。',
  },
  {
    id: 'colorless-skill-10',
    name: '祓い清め',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '保留。手札のカードを3枚まで廃棄する。廃棄。',
    effectPlus: '保留。手札のカードを5枚まで廃棄する。廃棄。',
  },
  {
    id: 'colorless-skill-11',
    name: 'スプラッシュ',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '他のキャラクターのランダムなアタックを3枚見て1枚を選び、手札に加える。このターン、それはコストを支払わずにプレイできる。',
    effectPlus: '他のキャラクターのランダムなアップグレード済みのアタックを3枚見て1枚を選び、手札に加える。このターン、それはコストを支払わずにプレイできる。',
  },
  {
    id: 'colorless-skill-12',
    name: '究極の防御',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 11,
    plusValue: 15,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '11ブロックを得る。',
    effectPlus: '15ブロックを得る。',
  },
  {
    id: 'colorless-skill-13',
    name: '発見',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '3枚のランダムなカードから1枚を選び、手札に加える。このターン、それはコストを支払わずにプレイできる。廃棄。',
    effectPlus: '3枚のランダムなカードから1枚を選び、手札に加える。このターン、それはコストを支払わずにプレイできる。',
  },
  {
    id: 'colorless-skill-14',
    name: '均衡',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 13,
    plusValue: 16,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '13ブロックを得る。このターン、手札をすべて保留する。',
    effectPlus: '16ブロックを得る。このターン、手札をすべて保留する。',
  },
  {
    id: 'colorless-skill-15',
    name: '衝撃波',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'すべての敵に脱力3と弱体3を付与する。廃棄。',
    effectPlus: 'すべての敵に脱力5と弱体5を付与する。廃棄。',
  },
  {
    id: 'colorless-skill-16',
    name: '天変地異',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札にあるカードをランダムに2枚プレイする。',
    effectPlus: '山札にあるカードをランダムに3枚プレイする。',
  },
  {
    id: 'colorless-skill-17',
    name: '爆弾',
    type: 'skill',
    rarity: 'アンコモン',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 40,
    plusValue: 50,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カウントが0になると、すべての敵に40ダメージを与える。（爆発まであと3ターン）',
    effectPlus: 'カウントが0になると、すべての敵に50ダメージを与える。（爆発まであと3ターン）',
  },
  {
    id: 'colorless-skill-18',
    name: 'シークレットウェポン',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札からアタックを1枚手札に加える。廃棄。',
    effectPlus: '山札からアタックを1枚手札に加える。',
  },
  {
    id: 'colorless-skill-19',
    name: 'シークレットテクニック',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札からスキルを1枚手札に加える。廃棄。',
    effectPlus: '山札からスキルを1枚手札に加える。',
  },
  {
    id: 'colorless-skill-20',
    name: '戦略家',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを3枚引く。廃棄。',
    effectPlus: 'カードを4枚引く。廃棄。',
  },
  {
    id: 'colorless-skill-21',
    name: '背水の陣',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 50,
    plusValue: 75,
    aggregatable: true,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '50ブロックを得る。この戦闘中、ブロックできずに攻撃ダメージを受けた場合、即死する。',
    effectPlus: '75ブロックを得る。この戦闘中、ブロックできずに攻撃ダメージを受けた場合、即死する。',
  },
  {
    id: 'colorless-skill-22',
    name: '隠された宝石',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札にあるリプレイを持たないランダムなカード1枚が、リプレイ2を得る。',
    effectPlus: '山札にあるリプレイを持たないランダムなカード1枚が、リプレイ3を得る。',
  },
  {
    id: 'colorless-skill-23',
    name: '聖なる選別',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札にあるすべてのレアカードを手札に加える。廃棄。',
    effectPlus: '保留。山札にあるすべてのレアカードを手札に加える。廃棄。',
  },
  {
    id: 'colorless-skill-24',
    name: '走り書き',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '手札がいっぱいになるまでカードを引く。廃棄。',
    effectPlus: '保留。手札がいっぱいになるまでカードを引く。廃棄。',
  },
  {
    id: 'colorless-skill-25',
    name: '錬金術',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ランダムなポーションを1つ入手する。廃棄。',
    effectPlus: 'ランダムなポーションを1つ入手する。廃棄。',
  },
  {
    id: 'colorless-skill-26',
    name: 'ビートダウン',
    type: 'skill',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '捨て札からランダムなアタックを3枚プレイする。',
    effectPlus: '捨て札からランダムなアタックを4枚プレイする。',
  },
  {
    id: 'colorless-power-01',
    name: '威風堂々',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 0,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 10,
    plusValue: 14,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '1ターンの間にカードを5枚プレイするたび、すべての敵に10ダメージを与える。',
    effectPlus: '1ターンの間にカードを5枚プレイするたび、すべての敵に14ダメージを与える。',
  },
  {
    id: 'colorless-power-02',
    name: 'ウォームアップ',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、活力4を得る。',
    effectPlus: 'ターン開始時、活力6を得る。',
  },
  {
    id: 'colorless-power-03',
    name: 'オートメーション',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'カードを10枚引くたび、●を得る。',
    effectPlus: 'カードを10枚引くたび、●を得る。',
  },
  {
    id: 'colorless-power-04',
    name: '計略',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '山札をシャッフルするたび、そこからカードを1枚選び、手札に加える。',
    effectPlus: '山札をシャッフルするたび、そこからカードを1枚選び、手札に加える。',
  },
  {
    id: 'colorless-power-05',
    name: '締め直し',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'block',
    baseValue: 4,
    plusValue: 6,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '防御カードから追加で4ブロックを得る。',
    effectPlus: '防御カードから追加で6ブロックを得る。',
  },
  {
    id: 'colorless-power-06',
    name: '武勇',
    type: 'power',
    rarity: 'アンコモン',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '筋力1を得る。敏捷1を得る。',
    effectPlus: '筋力2を得る。敏捷2を得る。',
  },
  {
    id: 'colorless-power-07',
    name: 'エントロピー',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、手札のカードを1枚変化させる。',
    effectPlus: '天賦。ターン開始時、手札のカードを1枚変化させる。',
  },
  {
    id: 'colorless-power-08',
    name: '郷愁',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 1,
    starCostBase: 0,
    energyCostPlus: 0,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: '毎ターン、最初にプレイするアタックまたはスキルは、山札の一番上に置かれる。',
    effectPlus: '毎ターン、最初にプレイするアタックまたはスキルは、山札の一番上に置かれる。',
  },
  {
    id: 'colorless-power-09',
    name: '騒乱',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 2,
    starCostBase: 0,
    energyCostPlus: 1,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、山札の一番上にあるカードをプレイする。',
    effectPlus: 'ターン開始時、山札の一番上にあるカードをプレイする。',
  },
  {
    id: 'colorless-power-10',
    name: 'カラミティ',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 2,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'アタックをプレイするたび、ランダムなアタックを1枚手札に加える。',
    effectPlus: 'アタックをプレイするたび、ランダムなアタックを1枚手札に加える。',
  },
  {
    id: 'colorless-power-11',
    name: '大岩転がし',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'damage',
    baseValue: 5,
    plusValue: 10,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'ターン開始時、すべての敵に5ダメージを与え、このダメージを5増加させる。',
    effectPlus: 'ターン開始時、すべての敵に10ダメージを与え、このダメージを5増加させる。',
  },
  {
    id: 'colorless-power-12',
    name: '不滅の鎧',
    type: 'power',
    rarity: 'レア',
    energyCostBase: 3,
    starCostBase: 0,
    energyCostPlus: 3,
    starCostPlus: 0,
    valueKind: 'none',
    baseValue: null,
    plusValue: null,
    aggregatable: false,
    starGainBase: null,
    starGainPlus: null,
    effectBase: 'プレート9を得る。',
    effectPlus: 'プレート12を得る。',
  },
];
